Repository storyofams/next-boilerplate, pull requests merged in 2021-03, with the labels that each got.

#70 [feat] api decorators
  .babelrc
  package.json
  src/__tests__/pages/api/sitemap.test.ts
  src/lib/handlers/index.ts
  src/lib/handlers/sitemapHandler/index.ts
  src/lib/handlers/sitemapHandler/sitemapHandler.test.ts
  src/pages/api/sitemap.ts
  tsconfig.json
  yarn.lock
Labels: Type: Feature, Type: Refactoring

#73 feat(lighthouse): 🚀 lighthouse on vercel deployment url
  .github/workflows/test.yaml
Labels: Priority: Medium, Status: Review Needed, Type: CI, Type: Feature, Type: Testing

#75 feat(react-ui): 🚀 updated to v1.2.0-beta.1
  .babelrc
  .vscode/settings.json
  package.json
  public/static/fonts/stylesheet.css
  src/components/common/Image/image.stories.tsx
  src/components/common/Image/index.tsx
  src/components/home/background/index.tsx
  src/pages/_app.tsx
  src/pages/_error.tsx
  src/pages/index.tsx
  src/styles/CSSreset.ts
  src/styles/fonts.ts
  src/styles/styled.d.ts
  src/styles/theme/button.ts
  src/styles/theme/form.ts
  src/styles/theme/index.ts
  src/styles/theme/link.ts
  src/styles/theme/space.ts
  src/styles/theme/text.ts
  src/styles/theme/variants.ts
  yarn.lock
Labels: Priority: Medium, Status: Review Needed, Type: Breaking Change, Type: Refactoring
